### ISSUE TITLE
Error: `by` can't contain join column `GENOMIC_CHANGE` which is missing from RHS Execution halted

### ISSUE THREAD

**Issue by shukwong** [sigven/pcgr#24]
Thanks for the wonderful too! I am trying out the new 6.0 and really like it. 
While most samples finished ok some of the samples had the following issue. I was wondering if you have an insight on why this is the case?

Thanks,
Wendy

2018-04-28 15:55:37 [INFO] Number of protein-coding variants: 0
2018-04-28 15:55:37 [INFO] Looking up SNV/InDel biomarkers for precision oncology - any tumortype
2018-04-28 15:55:37 [INFO] 0 clinical evidence item(s) found .. mapping = exact
2018-04-28 15:55:37 [INFO] 0 clinical evidence item(s) found .. mapping = codon
2018-04-28 15:55:39 [INFO] 0 clinical evidence item(s) found .. mapping = exon
Error: `by` can't contain join column `GENOMIC_CHANGE` which is missing from RHS
Execution halted

**Comment by sigven** [comment]
Hi,

Thanks for reporting this. Very likely an exception that has not been caught properly. Would you mind share your input VCF with me?

best,
Sigve

**Comment by shukwong** [comment]
Thanks for the prompt reply!
I can't send the entire VCF since it's patient data but here is the variant that causes the issue in a different sample. If I remove this variant the program finishes successfully. 
Thanks!
Wendy

chr4	1803568	COSM715	C	G	2671.14	PASS	AF=0.250627;AO=642;DP=2582;FAO=500;FDP=1995;FR=.;FRO=1495;FSAF=285;FSAR=215;FSRF=794;FSRR=701;FWDB=0.0110788;FXX=0.00249999;HRUN=4;HS;LEN=1;MLLD=122.808;QD=5.35566;RBI=0.0211602;REFB=0.00964977;REVB=0.0180281;RO=1933;SAF=367;SAR=275;SRF=1030;SRR=903;SSEN=0;SSEP=0;SSSB=0.0497858;STB=0.529484;STBP=0.165;TYPE=snp;VARB=-0.0285381;OID=COSM715;OPOS=1803568;OREF=C;OALT=G;OMAPALT=G;FUNC=[{'origPos':'1803568','origRef':'C','normalizedRef':'C','gene':'FGFR3','normalizedPos':'1803568','normalizedAlt':'G','polyphen':'1.0','gt':'pos','codon':'TGC','coding':'c.746C>G','sift':'0.0','grantham':'112.0','transcript':'NM_000142.4','function':'missense','protein':'p.Ser249Cys','location':'exonic','origAlt':'G','exon':'7','oncomineGeneClass':'Gain-of-Function','oncomineVariantClass':'Hotspot'}]	GT:GQ:DP:FDP:RO:FRO:AO:FAO:AF:SAR:SAF:SRF:SRR:FSAR:FSAF:FSRF:FSRR	0/1:99:2582:1995:1933:1495:642:500:0.250627:275:367:1030:903:215:285:794:701

**Comment by sigven** [comment]
Thanks, I believe I have reproduced the error now, and discovered the bug. Will be corrected in the next release, shortly. Thanks again for the bug report!

Sigve

**Comment by shukwong** [comment]
Great, thanks Sigve!

**Comment by sigven** [comment]
Would you mind trying this to see if it works now?
* `docker pull sigven/pcgr:0.6.1` 
* rename the version variable at the top of your pcgr.py script: `version = '0.6.1'`

**Comment by shukwong** [comment]
I am still getting the same error. could I provide you more information?

**Comment by sigven** [comment]
I'll look some more into it. More to come

**Comment by shukwong** [comment]
Thanks! I forgot to mention that I am running it with tumor_only mode.

**Comment by sigven** [comment]
You can retry 0.6.1 (docker pull)

**Comment by sigven** [comment]
Fixed in 0.6.1
